// ============================================================================
// templates.js — 9 resume template definitions for DOCX generation
// ============================================================================

const TEMPLATES = {
  // ── Single-Column Templates (ATS-Safe) ──

  classic: {
    id: "classic",
    name: "Classic",
    layout: "single-column",
    atsWarning: false,
    description: "Traditional format with bold headers",
    colors: {
      primary: "000000",
      accent: "000000",
      bodyText: "333333",
      subtleText: "666666",
      sidebarBg: null,
      sidebarText: null,
    },
    fonts: {
      name:           { face: "Calibri", size: 26 },
      contact:        { face: "Calibri", size: 20 },
      sectionHeading: { face: "Calibri", size: 22, allCaps: true },
      company:        { face: "Calibri", size: 21 },
      title:          { face: "Calibri", size: 21 },
      body:           { face: "Calibri", size: 20 },
      skillsCategory: { face: "Calibri", size: 20 },
      skillsItems:    { face: "Calibri", size: 20 },
      education:      { face: "Calibri", size: 20 },
    },
    sectionHeader: {
      bottomBorder: null,
      topBorder: null,
      shading: null,
      spacing: { before: 240, after: 120 },
    },
    page: {
      margins: { top: 720, bottom: 720, left: 1080, right: 1080 },
    },
    nameAlignment: "CENTER",
    sidebar: null,
  },

  elegant: {
    id: "elegant",
    name: "Elegant",
    layout: "single-column",
    atsWarning: false,
    description: "Teal accent headers with decorative borders",
    colors: {
      primary: "1A7A7A",
      accent: "1A7A7A",
      bodyText: "333333",
      subtleText: "666666",
      sidebarBg: null,
      sidebarText: null,
    },
    fonts: {
      name:           { face: "Georgia", size: 28 },
      contact:        { face: "Calibri", size: 20 },
      sectionHeading: { face: "Georgia", size: 22, allCaps: true },
      company:        { face: "Calibri", size: 21 },
      title:          { face: "Calibri", size: 21 },
      body:           { face: "Calibri", size: 20 },
      skillsCategory: { face: "Calibri", size: 20 },
      skillsItems:    { face: "Calibri", size: 20 },
      education:      { face: "Calibri", size: 20 },
    },
    sectionHeader: {
      bottomBorder: { style: "single", color: "1A7A7A", size: 6 },
      topBorder: null,
      shading: null,
      spacing: { before: 260, after: 100 },
    },
    page: {
      margins: { top: 720, bottom: 720, left: 1080, right: 1080 },
    },
    nameAlignment: "CENTER",
    sidebar: null,
  },

  "single-column": {
    id: "single-column",
    name: "Single Column",
    layout: "single-column",
    atsWarning: false,
    description: "Clean modern layout with blue accents",
    colors: {
      primary: "2B579A",
      accent: "2B579A",
      bodyText: "333333",
      subtleText: "666666",
      sidebarBg: null,
      sidebarText: null,
    },
    fonts: {
      name:           { face: "Calibri", size: 28 },
      contact:        { face: "Calibri", size: 20 },
      sectionHeading: { face: "Calibri", size: 22, allCaps: true },
      company:        { face: "Calibri", size: 21 },
      title:          { face: "Calibri", size: 21 },
      body:           { face: "Calibri", size: 20 },
      skillsCategory: { face: "Calibri", size: 20 },
      skillsItems:    { face: "Calibri", size: 20 },
      education:      { face: "Calibri", size: 20 },
    },
    sectionHeader: {
      bottomBorder: { style: "single", color: "2B579A", size: 6 },
      topBorder: null,
      shading: null,
      spacing: { before: 260, after: 100 },
    },
    page: {
      margins: { top: 720, bottom: 720, left: 1080, right: 1080 },
    },
    nameAlignment: "LEFT",
    sidebar: null,
  },

  "ivy-league": {
    id: "ivy-league",
    name: "Ivy League",
    layout: "single-column",
    atsWarning: false,
    description: "Formal style with horizontal rule separators",
    colors: {
      primary: "000000",
      accent: "333333",
      bodyText: "333333",
      subtleText: "666666",
      sidebarBg: null,
      sidebarText: null,
    },
    fonts: {
      name:           { face: "Georgia", size: 28 },
      contact:        { face: "Calibri", size: 20 },
      sectionHeading: { face: "Georgia", size: 22, allCaps: true },
      company:        { face: "Calibri", size: 21 },
      title:          { face: "Calibri", size: 21 },
      body:           { face: "Calibri", size: 20 },
      skillsCategory: { face: "Calibri", size: 20 },
      skillsItems:    { face: "Calibri", size: 20 },
      education:      { face: "Calibri", size: 20 },
    },
    sectionHeader: {
      bottomBorder: { style: "single", color: "000000", size: 8 },
      topBorder: null,
      shading: null,
      spacing: { before: 280, after: 100 },
    },
    page: {
      margins: { top: 720, bottom: 720, left: 1080, right: 1080 },
    },
    nameAlignment: "CENTER",
    sidebar: null,
  },

  // ── Two-Column Templates (ATS Warning) ──

  modern: {
    id: "modern",
    name: "Modern",
    layout: "two-column",
    atsWarning: true,
    description: "Left sidebar with contact and skills",
    colors: {
      primary: "2B579A",
      accent: "2B579A",
      bodyText: "333333",
      subtleText: "666666",
      sidebarBg: "F0F4F8",
      sidebarText: "333333",
    },
    fonts: {
      name:           { face: "Calibri", size: 26 },
      contact:        { face: "Calibri", size: 18 },
      sectionHeading: { face: "Calibri", size: 21, allCaps: true },
      company:        { face: "Calibri", size: 20 },
      title:          { face: "Calibri", size: 20 },
      body:           { face: "Calibri", size: 19 },
      skillsCategory: { face: "Calibri", size: 19 },
      skillsItems:    { face: "Calibri", size: 19 },
      education:      { face: "Calibri", size: 19 },
    },
    sectionHeader: {
      bottomBorder: { style: "single", color: "2B579A", size: 4 },
      topBorder: null,
      shading: null,
      spacing: { before: 200, after: 80 },
    },
    page: {
      margins: { top: 540, bottom: 540, left: 0, right: 720 },
    },
    nameAlignment: "LEFT",
    sidebar: {
      position: "left",
      widthDxa: 3200,
      mainWidthDxa: 7200,
      sidebarSections: ["contact", "skills", "education"],
      mainSections: ["summary", "experience"],
    },
  },

  timeline: {
    id: "timeline",
    name: "Timeline",
    layout: "two-column",
    atsWarning: true,
    description: "Teal sidebar with timeline-style experience",
    colors: {
      primary: "1A7A7A",
      accent: "1A7A7A",
      bodyText: "333333",
      subtleText: "666666",
      sidebarBg: "1A7A7A",
      sidebarText: "FFFFFF",
    },
    fonts: {
      name:           { face: "Calibri", size: 26 },
      contact:        { face: "Calibri", size: 18 },
      sectionHeading: { face: "Calibri", size: 21, allCaps: true },
      company:        { face: "Calibri", size: 20 },
      title:          { face: "Calibri", size: 20 },
      body:           { face: "Calibri", size: 19 },
      skillsCategory: { face: "Calibri", size: 19 },
      skillsItems:    { face: "Calibri", size: 19 },
      education:      { face: "Calibri", size: 19 },
    },
    sectionHeader: {
      bottomBorder: null,
      topBorder: null,
      shading: null,
      spacing: { before: 200, after: 80 },
    },
    page: {
      margins: { top: 540, bottom: 540, left: 0, right: 720 },
    },
    nameAlignment: "LEFT",
    sidebar: {
      position: "left",
      widthDxa: 3200,
      mainWidthDxa: 7200,
      sidebarSections: ["contact", "skills", "education"],
      mainSections: ["summary", "experience"],
    },
  },

  polished: {
    id: "polished",
    name: "Polished",
    layout: "two-column",
    atsWarning: true,
    description: "Dark blue right sidebar with name and skills",
    colors: {
      primary: "1B2A4A",
      accent: "1B2A4A",
      bodyText: "333333",
      subtleText: "666666",
      sidebarBg: "1B2A4A",
      sidebarText: "FFFFFF",
    },
    fonts: {
      name:           { face: "Calibri", size: 26 },
      contact:        { face: "Calibri", size: 18 },
      sectionHeading: { face: "Calibri", size: 21, allCaps: true },
      company:        { face: "Calibri", size: 20 },
      title:          { face: "Calibri", size: 20 },
      body:           { face: "Calibri", size: 19 },
      skillsCategory: { face: "Calibri", size: 19 },
      skillsItems:    { face: "Calibri", size: 19 },
      education:      { face: "Calibri", size: 19 },
    },
    sectionHeader: {
      bottomBorder: null,
      topBorder: null,
      shading: null,
      spacing: { before: 200, after: 80 },
    },
    page: {
      margins: { top: 540, bottom: 540, left: 720, right: 0 },
    },
    nameAlignment: "LEFT",
    sidebar: {
      position: "right",
      widthDxa: 3200,
      mainWidthDxa: 7200,
      sidebarSections: ["contact", "skills", "education"],
      mainSections: ["summary", "experience"],
    },
  },

  creative: {
    id: "creative",
    name: "Creative",
    layout: "two-column",
    atsWarning: true,
    description: "Dark blue left sidebar with name and contact",
    colors: {
      primary: "2B579A",
      accent: "2B579A",
      bodyText: "333333",
      subtleText: "666666",
      sidebarBg: "1B2A4A",
      sidebarText: "FFFFFF",
    },
    fonts: {
      name:           { face: "Calibri", size: 26 },
      contact:        { face: "Calibri", size: 18 },
      sectionHeading: { face: "Calibri", size: 21, allCaps: true },
      company:        { face: "Calibri", size: 20 },
      title:          { face: "Calibri", size: 20 },
      body:           { face: "Calibri", size: 19 },
      skillsCategory: { face: "Calibri", size: 19 },
      skillsItems:    { face: "Calibri", size: 19 },
      education:      { face: "Calibri", size: 19 },
    },
    sectionHeader: {
      bottomBorder: { style: "single", color: "2B579A", size: 4 },
      topBorder: null,
      shading: null,
      spacing: { before: 200, after: 80 },
    },
    page: {
      margins: { top: 540, bottom: 540, left: 0, right: 720 },
    },
    nameAlignment: "LEFT",
    sidebar: {
      position: "left",
      widthDxa: 3200,
      mainWidthDxa: 7200,
      sidebarSections: ["contact", "skills"],
      mainSections: ["summary", "experience", "education"],
    },
  },

  stylish: {
    id: "stylish",
    name: "Stylish",
    layout: "two-column",
    atsWarning: true,
    description: "Dark sidebar with blue accents",
    colors: {
      primary: "4A90D9",
      accent: "4A90D9",
      bodyText: "333333",
      subtleText: "666666",
      sidebarBg: "2D2D2D",
      sidebarText: "FFFFFF",
    },
    fonts: {
      name:           { face: "Calibri", size: 26 },
      contact:        { face: "Calibri", size: 18 },
      sectionHeading: { face: "Calibri", size: 21, allCaps: true },
      company:        { face: "Calibri", size: 20 },
      title:          { face: "Calibri", size: 20 },
      body:           { face: "Calibri", size: 19 },
      skillsCategory: { face: "Calibri", size: 19 },
      skillsItems:    { face: "Calibri", size: 19 },
      education:      { face: "Calibri", size: 19 },
    },
    sectionHeader: {
      bottomBorder: null,
      topBorder: null,
      shading: null,
      spacing: { before: 200, after: 80 },
    },
    page: {
      margins: { top: 540, bottom: 540, left: 0, right: 720 },
    },
    nameAlignment: "LEFT",
    sidebar: {
      position: "left",
      widthDxa: 3200,
      mainWidthDxa: 7200,
      sidebarSections: ["contact", "skills", "education"],
      mainSections: ["summary", "experience"],
    },
  },
};

module.exports = { TEMPLATES };
